services:
  - mongo:3.6

stages:
  - test
  # - build
  - deploy

variables:
  DATABASE: "mongodb://mongo/futureflix"


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#
# don’t cache node_modules when running tests
# against different Node.js versions to avoid
# NPM install issues for packages that compile
# against a specific version
#
# cache:
#   paths:
#   - node_modules/


before_script:
  - npm install

# test against Node.js v8 and latest stable release
test:node-8:
  stage: test
  image: node:8
  script:
    - npm test

test:node-latest:
  stage: test
  image: node:latest
  script:
    - npm test

# build:
#   stage: build
#   image: node:8
#   script: echo "Building the app"

deploy:
  stage: deploy
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - ssh-keyscan futureflix.space >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Starting Futureflix production deployment"
    - ssh launch@futureflix.space "cd futureflix && git pull origin master"
    - ssh launch@futureflix.space "cd futureflix && npm install --production"
  only:
  - master
  - develop