services:
  - mongo:3.6

stages:
  - test
  - build
  - deploy

variables:
  DATABASE: "mongodb://mongo/futureflix"


# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
#
# don’t cache node_modules when running tests
# against different Node.js versions to avoid
# NPM install issues for packages that compile
# against a specific version
#
# cache:
#   paths:
#   - node_modules/


before_script:
  - npm install

# test against Node.js v8 and latest stable release
test:node-8:
  stage: test
  image: node:8
  script:
    - npm test

test:node-latest:
  stage: test
  image: node:latest
  script:
    - npm test

build:
  stage: build
  script: echo "Building the app"

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$PRODUCTION_PRIVATE_KEY")
  script:
    - echo "Deploy to Futureflix production server"
    - ssh -p22 launch@futureflix.space "cd futureflix && git pull origin master"
    - ssh -p22 launch@futureflix.space "cd futureflix && npm install --production"
  only:
  - master
  - develop