services:
  - mongo:3.4

variables:
  DATABASE: "mongodb://mongo/futureflix"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - npm install

# test against Node.js v8 and latest stable release
test:node-8:
  image: node:8
  script:
    - npm test

test:node-latest:
  image: node:latest
  script:
    - npm test
