image: node:8

services:
  - mongo:3.4

variables:
  DATABASE: "mongodb://mongo/futureflix"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - npm install

test:
  script:
    - npm test